### ISSUE TITLE
Support for custom entity types?

### ISSUE THREAD

**Issue by akashgupta88** [asafyish/predictionio-driver#1]
Hi Asaf,

I see from the code that the event types are hard coded to be 'pio-user' and 'pio-item' based on the examples and tutorials given in the Prediction.io website. Just wanted to know if I can use custom entity-types in the code? For eg. Entity types like 'user' and 'dish'.

If required, I could modify the existing code for events and send over a pull request.

**Comment by garrett-gottlieb** [comment]
I'd urge you to reopen this. The methods `createUser`, `createItem`, and `createAction` should not *overwrite* the `entityType` and `targetEntityType`, as those should be customizable. Setting defaults is fine.
