### ISSUE TITLE
NPM package not up-to-date with repo

### ISSUE THREAD

**Issue by RakanNimer** [asafyish/predictionio-driver#12]
Hey @asafyish,

First, thanks for building this driver, it's exactly what I needed and has been very helpful.

The package on npm contains the code before commit [68a3fdcdbc81efd3e10ca63a3b29f5d590cc6ce6](https://github.com/asafyish/predictionio-driver/commit/68a3fdcdbc81efd3e10ca63a3b29f5d590cc6ce6)
which doesn't work (doesn't parse request body).

Installing from asafyish/predictionio-driver works perfectly.

Cheers !

**Comment by asafyish** [comment]
Fixed. Version 0.5.0 is on npm.
