### ISSUE TITLE
The entityType pio_user is not allowed. \'pio_\' is a reserved name prefix.

### ISSUE THREAD

**Issue by victorleungtw** [asafyish/predictionio-driver#3]
I am trying to register a new user, but I get the following error message:

{ message: 'java.lang.IllegalArgumentException: requirement failed: The entityType pio_user is not allowed. \'pio_\' is a reserved name prefix.' }

I am guessing the entityType should be 'user' instead of 'pio_user' in your events-client.js

**Comment by asafyish** [comment]
Thanks for the report !
Just merged your PR and published a new version !
